### ISSUE TITLE
Tweet stubs

### ISSUE THREAD

**Issue by katieannemills** [mozillascience/Collaborate#1]
Putting the 'who we are' paragraph in the project stubs comes out sounding a bit weird; @acabunoc suggested replacing these with tweet summaries. Can do, but want this done and out to researchers for review by tomorrow morning - is this possible in this timeframe?

**Comment by katieannemills** [comment]
(ie, I can write the tweet summaries if @acabunoc has time to point the stub text at a new db key).

**Comment by abbycabs** [comment]
I think most of them are already pretty good summaries (though, maybe a _bit_ too long to be tweetable). Do we need a whole new key?

**Comment by katieannemills** [comment]
I think so. Some of them are really long, and worse, some of them don't really make any sense as the first words out of a project's mouth.

Are we worried about db bloat? Now that we've totally migrated to the who/what model, the old 'summary' key isn't actually being used for anything.

**Comment by abbycabs** [comment]
No, not db bloat. I just think we don't need 'tweetable summary' AND 'who/what'. I think tweetable summary + what(maybe with 'who' rolled in) would work well.

**Comment by abbycabs** [comment]
Thought it over again. I could make a tweetable summary that's pre-populated with 'who' right now, then you can ask the groups to edit it through the interface the next few days

**Comment by katieannemills** [comment]
Where will the edits go? Into a new key, or overwriting who?

**Comment by abbycabs** [comment]
New key for now. Updated:
http://abby-contrib.herokuapp.com/

I still think tweetable + who + what might be overkill. But they all exist on the page now. Might supress 'WHO' if it gets too redundant.

**Comment by abbycabs** [comment]
You had admin access so you can go ahead and edit the first paragraph on the project pages to give them a tweetable summary different from the 'WHO' section

**Comment by katieannemills** [comment]
Cool, thanks! 

Also: I actually agree the ideal would be tweet + combo of who/what, but redoing the who/what would be the third time I've asked people to rewrite their content - we're launching this week, need to put a hard stop on major rewrites :)

**Comment by katieannemills** [comment]
(but so - what's the new key? are you going to update the JSON repo or can I just start sticking tweets in there and upload when I'm done?)

**Comment by katieannemills** [comment]
ah - 'tweetable'. Cool! Will close this issue once I've got tweets in place for all the projects.

(PS: the edit interface you build is AWESOME, thanks so much!)

**Comment by abbycabs** [comment]
Oh sorry - yeah I didn't actually edit the db on this one...  might be hard to sync the db with the json repo with the edit interface now. Sorry.

**Comment by katieannemills** [comment]
why? I was just going to use your edit interface to write all the tweets, `mongoexport` the whole db and put it in the repo - is this a terrible idea for unforeseen reasons?

**Comment by abbycabs** [comment]
Well, the different projects will be able to edit the db. We won't be able to manually export for each edit. Can the actual db be our central data system?

**Comment by katieannemills** [comment]
Oh right, yep that's fine - the repo version was more for you and I to keep on top of each other's edits over the past few days. We can retire it once we go to production (although of course someone somewhere will be making nightly db backups...?)

**Comment by abbycabs** [comment]
Sounds good. Backups are a good idea.

**Comment by katieannemills** [comment]
tweets complete for existing content :)
